### ISSUE TITLE
希望大大能加一个运行程序参数的选择

### ISSUE THREAD

**Issue by Insvl1129** [KamenRiderKuuga/ProcessGuard#2]
有些程序需要带参数启动, 发现无法加参数~

**Comment by KamenRiderKuuga** [comment]
> 有些程序需要带参数启动, 发现无法加参数~

在配置里加一列启动参数列，然后填写要附带的参数字符串咋样，比如程序是记事本，填的参数是`/A filename.txt`到时候启动的时候效果就像`notepad.exe /A filename.txt`

**Comment by Insvl1129** [comment]
不是很明白啊, json格式的文件中, 文件后面加参数吗

**Comment by Insvl1129** [comment]
测试了，不行~

**Comment by Insvl1129** [comment]
``感谢!

**Comment by KamenRiderKuuga** [comment]
@Insvl1129 好啦，加了这个功能
https://github.com/KamenRiderKuuga/ProcessGuard/releases/tag/v1.1

![image](https://user-images.githubusercontent.com/39508075/162587149-2be5e773-4d94-438e-a897-85b443d83a2e.png)

**Comment by Insvl1129** [comment]
非常感谢 三连支持
