### ISSUE TITLE
程序貌似在Windows server 2012 R2上无法启动程序 服务可以正常运行

### ISSUE THREAD

**Issue by airdm** [KamenRiderKuuga/ProcessGuard#4]
如标题.开启后没有反应.测试在WIN11上可以正常运行.

**Comment by airdm** [comment]
我对C#不太了解, 是不是需要安装相应的环境包. 因为服务器上基本没有安装什么依赖包

**Comment by KamenRiderKuuga** [comment]
@airdm 那个配置界面可以正常出现并且进行配置，但是点击启动没有反应对吗，启动的是一个什么进程呢

**Comment by airdm** [comment]
我在WIN11上正常可以使用并正常运行了我想要启动的exe程序.

**Comment by airdm** [comment]
在2012上运行的和我在WIN11 要启动的是相同的

**Comment by airdm** [comment]
关闭内置管理员账户的管理员批准模式，gpedit.msc - 计算机配置 - 安全设置 - 本地策略 - 安全选项 - 用户帐户控制：用于内置管理员帐户的管理批准模式选择已禁用即可，这样内置管理员帐户就能使用完整管理权限运行所有应用程序，而不会弹出提示让用户批准操作。此外，若禁用用户账户控制：以管理员批准模式运行所有管理员，则可以彻底关闭UAC的管理员审批模式

并且我也检查了你之前回答的相关内容  都已经禁用也无济于事

**Comment by airdm** [comment]
服务器上没有安装任何C语言相关的依赖包 比如C++ 2012 和 .NET 之类的. 是否跟这些有关呢.

**Comment by KamenRiderKuuga** [comment]
@airdm 目前还不能确定原因，我想我应该装一个Windows server 2012 R2试试，稍后给你答复哈

**Comment by airdm** [comment]
好的 谢谢你 你的这个工具很好用.我非常喜欢.可以用服务的形式守护进程 并且消耗很低 非常赞..

**Comment by KamenRiderKuuga** [comment]
@airdm 谢谢你的支持！我使用Windows Server 2012 R2服务器尝试复现了这个问题，最后发现是因为使用远程桌面会导致获取不到正确的Session ID，在新版本修复了这个问题，你可以下载使用看看：
https://github.com/KamenRiderKuuga/ProcessGuard/releases/tag/v1.5

相关代码：https://github.com/KamenRiderKuuga/ProcessGuard/commit/9c15c9d4b98b81a197fb03e7ba47b603cfa936eb

记得在界面上把原来的服务卸载了，再点击启动，因为这个改动涉及到服务

**Comment by airdm** [comment]
@KamenRiderKuuga 好了 他已经可以正常工作了.. 非常完美..点赞

**Comment by airdm** [comment]
@KamenRiderKuuga 我遇到了新的问题. 貌似ProcessGuard一直在尝试启动守护的进程 导致我的进程下面一直在闪烁

**Comment by airdm** [comment]
我把守护服务停止后 在点一下我的程序 就不会在闪烁了.
