### ISSUE TITLE
被守护的程序会一闪而过无法启动

### ISSUE THREAD

**Issue by zzh4n** [KamenRiderKuuga/ProcessGuard#7]
测试使用的是 `frpc`，会不停地弹出一个一闪而过的窗口，实际程序并没有正常运行

同样的配置在 `cmd` 和 `PowerShell` 中是可以正常使用的

进程名称：`frpc`
完整路径：`D:\frpc.exe`
启动参数：`-c "D:\frpc.ini"`
仅启动一次：□
最小化：□
无窗应用：□

**Comment by KamenRiderKuuga** [comment]
@zzh4n 抱歉，这段时间实在太忙了，没有及时回复消息。我试了一下，之所以会一闪而过，是因为`frpc.exe`没有正常成功启动造成的，因为本程序用的函数，其实相当于按`Win + R`按键，输入进程执行路径和参数来运行。按`Win + R`，输入`D:\frpc.exe -c "D:\frpc.ini"`并回车运行的结果会是：

```plaintext
This is a command line tool.

You need to open cmd.exe and run it from there.
```

所以实际上`frpc.exe`并没有被成功启动，在一直重启。而之所以不能通过这种方式成功启动，应该是由于`frpc.exe`自身的限制，如果要在启动时传递额外的参数，就必须通过命令行工具来运行

所以要守护`frpc.exe`，有两种方法：
1. 守护的进程路径填`D:\frpc.exe`，不填参数，因为`frpc.exe`会自动使用其所在目录的配置；
2. 守护的进程路径填`C:\Windows\System32\cmd.exe`，启动参数填`/k D:\frpc.exe -c "D:\frpc.ini"`

根据测试的情况来看，如果对配置文件路径没有特别的要求，用第一种配置方式会更好，因为如果使用第二种配置方式，是通过`cmd.exe`启动了`frpc.exe`，守护服务配置界面上的停止按钮功能会变得不能正常使用，因为只能获取到直接由守护服务启动的进程ID
